/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js. It is checked in here so TypeScript
// understands the app before the first local `next dev` run.
